### ISSUE TITLE
Skill: Electro-Arouse ?

### ISSUE THREAD

**Issue by NovaCrypt** [NovaCrypt/HeroicMightMGD#1]
Need to come up with a new skill for the mod. The steps to completing this are below...

### Progress

- [x] Brainstorm ideas
- [x] Settle on a plan
- [x] Create skill file
- [x] Initial testing
- [x] #6
- [x] Roll out skill

**Comment by alperozoner** [comment]
You could add lightning bolt from dota2.

**Comment by NovaCrypt** [comment]
Could you elaborate at all? Curious idea although the combat system for MGD is nothing like Dota...

**Comment by alperozoner** [comment]
Calls down a bolt of lightning to strike an enemy unit, causing damage and a mini-stun. When cast, Lightning Bolt briefly provides unobstructed vision and True Sight around the target in a 750 radius. Can be cast on the ground, affecting the closest enemy hero in 325 range.
Cast Animation 0.3s+0.67s
Cast Range: Affected by Cast Range bonuses. 700/750/800/850
Search Radius: 325
Vision/True Sight Radius: 750
Damage: 125/200/275/350
Stun Duration: 0.3 (Talent 0.7)
Vision/True Sight Duration: 5
True Sight Linger Duration: 0.5
Cooldown 6	
Mana 120/125/130/135

**Comment by NovaCrypt** [comment]
An interesting suggestion. Would have to be heavily adapted for balancing reasons and also the fact that MGD is a hentai game... Damage is dealt in the form of sexual arousal, but it still has magic and I could maybe adapt this to be some form of electrostatic arouse spell maybe? I'll do some thinking and see if I can make it work. Thanks for the suggestion!

**Comment by alperozoner** [comment]
Sure thing! I am more than happy to contribute.

**Comment by NovaCrypt** [comment]
Issue with acquisition method is now resolved. Turns out you can't yet add to a pre-existing skills shop in the game... The devs are working on that though.
